### PR TITLE
exception event refactoring

### LINKED ISSUE #11: refactor exception event tags

### PR DESCRIPTION
**Pull request by jking-netuitive**
closes #11

### CODE REVIEW

File: lib/netuitive_ruby_api.rb [hunk 1]
```diff
@@ -37,15 +37,15 @@ def clear_metrics
...
     end
 
     def event(message, timestamp = Time.new, title = 'Ruby Event', level = 'Info', source = 'Ruby Agent', type = 'INFO', tags = nil)
       server_interaction { netuitivedServer.event(message, timestamp, title, level, source, type, tags) }
     end
 
-    def exception_event(exception, klass = nill, uri = nil, controller = nil, action = nil)
-      server_interaction { netuitivedServer.exceptionEvent(exception, klass, uri, controller, action) }
+    def exception_event(exception, klass = nil, tags = nil)
+      server_interaction { netuitivedServer.exceptionEvent(exception, klass, tags) }
```
Comment (TheConnMan) [inline lib/netuitive_ruby_api.rb]: Redacting this comment, this function is the function I thought needed to be refactored.
